name: GH Issue Migrator
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      gh_ibm_token:
        description: 'GitHub Oauth Token for IBM'
        required: true
      zenhub_ibm_apikey:
        description: 'ZenHub API Key for IBM'
        required: false
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to create labels
    steps:
      - uses: slambdev/create-labels-action@v19
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_ibm_token: ${{ github.event.inputs.gh_ibm_token }}
          zenhub_ibm_apikey: ${{ github.event.inputs.zenhub_ibm_apikey }}
