name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      gh_ibm_token:
        description: 'GitHub Oauth Token for IBM'
        required: true
      zenhub_ibm_apikey:
        description: 'ZenHub API Key for IBM'
        required: false
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to create labels
    steps:
    - name: Create labels action step
      id: create-labels
      uses: slambdev/create-labels-action@v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
