name: Manual workflow
on: workflow_dispatch
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to create labels
    steps:
    - name: Create labels action step
      id: create-labels
      uses: slambdev/create-labels-action@v1
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
